# AUTOGENERATED! DO NOT EDIT! File to edit: 00_card.ipynb (unless otherwise specified).

__all__ = ['Card']

# Cell
import random
class Card:
    """This is a card
    Attributes:
    suit: integer 0-3
    """

    suit_names = ["Clubs", "Dimonds", "Hearts", "Spades"]
    rank_names = [None, "Ace", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King"]


    def __init__(self, suit=0, rank=2):
        self.suit = suit
        self.rank = rank

    def __str__(self):
        """Returns string representation"""
        return '%s of %s' % (Card.rank_names[self.rank],
                            Card.suit_names[self.suit])
    def __eq__(self, other):
        """Checks if cards have same suit
        returns:boolean
        """
        return self.suit == other.suit and self.rank == other.rank
    def __lt__(self,other):
        """Compares card to other first by suit than by rank
        returns: boolean
        """
        t1 = self.suit, self.rank
        t2 = other.suit, other.rank
        return t1 < t2
    __repr__ = __str__


